font_family      0xProto Nerd Font
bold_font        0xProto Nerd Font
italic_font      0xProto Nerd Font
bold_italic_font 0xProto Nerd Font
font_size 11.0

symbol_map U+E0A0-U+E0A3,U+E0C0-U+E0C7 PowerlineSymbols

scrollback_lines 2000

editor .

background #151622
foreground #cdd6f4

background_opacity 1.0
background_blur 0

selection_foreground #151622
selection_background #f5e0dc

# Black
color0 #151622
color8 #585e8f
# Red
color1 #F08080
color9 #F08080
# Green
color2  #a0d0a0
color10 #a0d0a0
# Yellow
color3  #dbd07f
color11 #dbd07f
# Blue
color4  #607bc3
color12 #607bc3
# Magenta
color5  #607bc3
color13 #607bc3
# Cyan
color6  #89b4fa
color14 #89b4fa
# White
color7  #a9b5d5
color15 #b6c0db
