dpi-aware=no
#icon-theme=Papirus-Dark
width=34
#font=0xProto:weight=bold:size=15
font=Arial:weight=bold:size=13
line-height=15
fields=name,generic,comment,categories,filename,keywords
terminal= alacrity
prompt="~   "
show-actions=yes
exit-on-keyboard-focus-loss=no

[colors]
background=151622dd
text=a9b5d5ff
prompt=b6c0dbff
placeholder=7f849cff
input=cdd6f4ff
match=89b4faff
selection=585b70ff
selection-text=cdd6f4ff
selection-match=89b4faff
counter=7f849cff
border=607bc3ff

[border]
radius=10
width=3

[dmenu]
exit-immediately-if-empty=yes

[key-bindings]
